
#=============================================================#
#POSTGRESQL CONFIG

spring.datasource.url=jdbc:postgresql://localhost:5432/enceasy
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#=============================================================#
#JPA / HIBERNATE CONFIG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#==============================================================#
#PORT

server.port=${PORT:8080}

#==============================================================#
#CONFIG BASE URL

app.base-url="${APP_BASE_URL}
app.code-length = 6